# ==========================================
# Profile: dev
# Banco H2 em memória + mock service nuvem
# ==========================================

# H2 em memória
spring.datasource.url=jdbc:h2:mem:scih_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 (acessível em /h2-console durante dev)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# URL do mock service (Railway/Render)
#scih.mock.base-url=https://mock-service-production.up.railway.app
scih.mock.base-url=https://scih-teste-production.up.railway.app

# Logs detalhados em dev
logging.level.com.scih=DEBUG
logging.level.org.springframework.web=DEBUG
